version: "3.8"

services:
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "3020:3020"
    environment:
      - PORT=3020
    working_dir: /app
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    command: npm run dev
    ports:
      - "8020:8020"
    environment:
      - PORT=8020
    working_dir: /app
    volumes:
      - ./backend:/app

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anclora_flow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ai-services:
    build: ./ai-services
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/anclora_flow
    working_dir: /app
    volumes:
      - ./ai-services:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
